name: Deploy the backend
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code or cloning the code
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push ## docker build and docker push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./dockerfile/Dockerfile.backend
          push: true
          tags: himanshumishra3198/chalk-app-backend:${{ github.sha }}
